org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true

# Kotlin code style (optionnel)
kotlin.code.style=official
# Évite les erreurs de cache quand le projet est sur un autre lecteur que le Pub cache
kotlin.incremental=false

# Build optimizations
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=true
android.nonTransitiveRClass=true
android.defaults.buildfeatures.buildconfig=true
android.nonFinalResIds=false
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
